make flake8-markdown a Makefile only linter

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -154,9 +154,10 @@ jobs:
             echo "::endgroup::"
             poetry run flake8 --format github ${{ steps.filter.outputs.python_files }}
 
-      - name: flake8-markdown
-        if: (success() || failure()) && steps.filter.outputs.markdown == 'true'
-        run: poetry run flake8-markdown ${{ steps.filter.outputs.markdown_files }}
+      # Disable: flake8-markdown does not use the pyproject.toml config correctly
+      # - name: flake8-markdown
+      #   if: (success() || failure()) && steps.filter.outputs.markdown == 'true'
+      #   run: poetry run flake8-markdown ${{ steps.filter.outputs.markdown_files }}
 
       - name: pylint
         if: (success() || failure()) && steps.filter.outputs.python_alone == 'true'
